remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Passion Project Research Blog
description: Researching the possibilities of WGSL, GLSL and TSL as a part of passion project for 3rd year of DEVINE.
